# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e35e6964d4121a77d228696ae900f7e24171a8a0d26cbb0109a14687b513e445101e95c68f25728766384884838d85a9f699a8a81aae325549101e11b6b88dc5

test:
  secret_key_base: 8c55f4666ed555b4dd5faed5bbc0222537859c60d34987b7a44eac6515a75760c33a472fe2a2802cc3909440f2bc1f26facc7afe1512ddcc9446eef504e2ec00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
